#!/usr/bin/env tsx
/**
 * Extract validator CBORs from plutus.json files and generate validators.ts
 * Run this after: aiken build
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface ValidatorConfig {
  name: string;
  plutusJsonPath: string;
  validatorTitle: string;
}

// Configuration for validators
const VALIDATORS: ValidatorConfig[] = [
  {
    name: 'group',
    plutusJsonPath: 'src/on-chain/build/packages/modulo-p-cardano-semaphore/plutus.json',
    validatorTitle: 'group.group.mint'
  },
  {
    name: 'semaphore',
    plutusJsonPath: 'src/on-chain/build/packages/modulo-p-cardano-semaphore/plutus.json',
    validatorTitle: 'semaphore.semaphore.mint'
  },
  {
    name: 'voting',
    plutusJsonPath: 'src/on-chain/plutus.json',
    validatorTitle: 'voting.voting.mint'
  }
];

interface ExtractedValidator {
  name: string;
  cbor: string;
  sourceHash: string;
  sourcePath: string;
}

function computeFileHash(filePath: string): string {
  const content = fs.readFileSync(filePath, 'utf-8');
  return crypto.createHash('sha256').update(content).digest('hex');
}

function extractValidator(config: ValidatorConfig): ExtractedValidator {
  const { name, plutusJsonPath, validatorTitle } = config;

  // Resolve path from project root
  const projectRoot = path.resolve(__dirname, '../../..');
  const fullPath = path.join(projectRoot, plutusJsonPath);

  if (!fs.existsSync(fullPath)) {
    throw new Error(`Plutus JSON not found: ${fullPath}\nDid you run 'aiken build'?`);
  }

  // Read and parse plutus.json
  const blueprint = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));

  // Find the validator
  const validator = blueprint.validators.find((v: any) => v.title === validatorTitle);

  if (!validator) {
    const available = blueprint.validators.map((v: any) => v.title).join(', ');
    throw new Error(
      `Validator '${validatorTitle}' not found in ${plutusJsonPath}\n` +
      `Available validators: ${available}`
    );
  }

  return {
    name,
    cbor: validator.compiledCode,
    sourceHash: computeFileHash(fullPath),
    sourcePath: plutusJsonPath
  };
}

function generateValidatorsFile(validators: ExtractedValidator[]): string {
  const timestamp = new Date().toISOString();

  // Generate metadata object
  const metadata = {
    generated: timestamp,
    sourceHashes: validators.reduce((acc, v) => {
      acc[v.name] = v.sourceHash;
      return acc;
    }, {} as Record<string, string>),
    sourcePaths: validators.reduce((acc, v) => {
      acc[v.name] = v.sourcePath;
      return acc;
    }, {} as Record<string, string>)
  };

  // Generate validators object
  const validatorsObj = validators.reduce((acc, v) => {
    acc[v.name] = { mint: v.cbor };
    return acc;
  }, {} as Record<string, { mint: string }>);

  // Generate TypeScript file content
  return `/**
 * Auto-generated validator constants
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated: ${timestamp}
 *
 * To regenerate after changing validators:
 *   1. Run: aiken build
 *   2. Run: npm run extract-validators
 *
 * Source files:
${validators.map(v => ` *   - ${v.name}: ${v.sourcePath}`).join('\n')}
 */

export interface ValidatorMetadata {
  generated: string;
  sourceHashes: Record<string, string>;
  sourcePaths: Record<string, string>;
}

export interface Validators {
  _metadata: ValidatorMetadata;
  group: { mint: string };
  semaphore: { mint: string };
  voting: { mint: string };
}

export const VALIDATORS: Validators = {
  _metadata: ${JSON.stringify(metadata, null, 2)},

  group: {
    mint: "${validatorsObj.group.mint}"
  },

  semaphore: {
    mint: "${validatorsObj.semaphore.mint}"
  },

  voting: {
    mint: "${validatorsObj.voting.mint}"
  }
};

/**
 * Get validator CBOR by name (browser-compatible)
 */
export function getValidatorCbor(name: 'group' | 'semaphore' | 'voting'): string {
  return VALIDATORS[name].mint;
}
`;
}

async function main() {
  console.log('🔍 Extracting validators from plutus.json files...\n');

  try {
    // Extract all validators
    const extracted: ExtractedValidator[] = [];

    for (const config of VALIDATORS) {
      console.log(`📄 Processing ${config.name}...`);
      console.log(`   Source: ${config.plutusJsonPath}`);
      console.log(`   Validator: ${config.validatorTitle}`);

      const validator = extractValidator(config);
      extracted.push(validator);

      console.log(`   ✅ Extracted (${validator.cbor.length} chars)`);
      console.log(`   Hash: ${validator.sourceHash.substring(0, 16)}...\n`);
    }

    // Generate validators.ts file
    const outputPath = path.resolve(__dirname, '../src/validators.ts');
    const content = generateValidatorsFile(extracted);

    fs.writeFileSync(outputPath, content, 'utf-8');

    console.log('✅ Successfully generated validators.ts');
    console.log(`   Output: ${outputPath}`);
    console.log(`   Size: ${(content.length / 1024).toFixed(2)} KB\n`);

    console.log('📊 Summary:');
    extracted.forEach(v => {
      console.log(`   - ${v.name}: ${(v.cbor.length / 1024).toFixed(2)} KB`);
    });

  } catch (error: any) {
    console.error('\n❌ Error:', error.message);
    process.exit(1);
  }
}

main();
